In [50]:
import numpy as np
import pandas as pd

## Introduction to NumPy

### Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
# List to NumPy array
a = np.array([1, 2, 3, 4, 5])
print(a[3])

4


In [8]:
# Range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [11]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multi-dimensional arrays

In [13]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a[0]) # Access the entire row
print(a[:, 1]) # Access the entire column

a[1, 1] = 20
print(a)

[1 2 3]
[2 5 8]
[[ 1  2  3]
 [ 4 20  6]
 [ 7  8  9]]


### Randomly generated arrays

In [21]:
np.random.seed(2) # For reproducibility
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [23]:
# Uniform distribution 
np.random.randn(5, 2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [25]:
# Generate array with random integers
np.random.randint(1, 10, size=(3,3))

array([[3, 9, 8],
       [2, 7, 9],
       [6, 4, 1]])

### Element-wise Operations

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
print(a+1)
print(a*2)
print((10 + (a*2)) ** 2)

[1 2 3 4 5]
[0 2 4 6 8]
[100 144 196 256 324]


In [31]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])
print(a/b)

[2. 2. 2.]


### Comparison operations

In [32]:
a = np.arange(10)
a >= 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [40]:
a = np.random.randint(1, 10, size=(10,))
b = np.random.randint(1, 10, size=(10,))
print(a, b)
print(a > b)
print(a[a > b])

[7 4 2 9 6 6 5 3 8 9] [8 4 5 9 7 4 9 9 6 2]
[False False False False False  True False False  True  True]
[6 8 9]


### Aggregation Functions

In [41]:
a

array([7, 4, 2, 9, 6, 6, 5, 3, 8, 9])

In [42]:
a.sum()

59

In [43]:
a.std()

2.3

In [44]:
print(a.min(), a.max())

2 9


## Linear Algebra Refresher

In [45]:
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 4))

In [47]:
# Dot product
c = a.dot(b)
print(c, c.shape)

[[ 84  52  80  44]
 [111  77 111  67]
 [108  63  93  54]] (3, 4)


In [49]:
# Matrix inversion 
print(np.linalg.inv(a))

[[ 0.66666667 -0.33333333 -0.11111111]
 [ 0.5         0.         -0.33333333]
 [-0.91666667  0.33333333  0.44444444]]


## Introduction to Pandas

### Data Frames 

The main data structure abstraction in `pandas`

In [51]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [52]:
df = pd.DataFrame(data, columns=columns)

In [53]:
df.head()

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

Alternatively, we can use a list of dictionaries to define a dataframe.

In [54]:
data = data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [55]:
df = pd.DataFrame(data)
df.head()

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

### Series

- Every column in a `pandas` dataframe is a series

In [56]:
print(df.Make)

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object


In [57]:
print(df["Make"])

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object


In [58]:
print(df[["Make", "Model"]])

      Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier


In [59]:
# Adda new column 
df["id"] = [1, 2, 3, 4, 5]

In [60]:
df.head(2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2

### Indexing

In [61]:
df.index 

RangeIndex(start=0, stop=5, step=1)

In [62]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [64]:
# Accessing elements (rows) using `loc`
df.loc[1]


Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: 1, dtype: object

In [65]:
# Accessing multiple rows
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  id  
1         Sedan  27150   2  
2   convertible  54990   3

In [66]:
# Assigning a new index 
df.index = ['a', 'b', 'c', 'd', 'e']

In [67]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
a         sedan   2000   1  
b         Sedan  27150   2  
c   convertible  54990   3  
d       4dr SUV  34450   4  
e        Pickup  32340   5

In [68]:
# Positional indexing 
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: b, dtype: object

In [71]:
df.iloc[0, 1]

'Stanza'

In [74]:
# Resetting index
df.reset_index(drop=True, inplace=True)

In [75]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

### Accessing Elements

### Element-wise Operations

In [76]:
df['Engine HP'] / 100 

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [77]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [78]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

### Filtering

In [79]:
df[df['Year'] >= 2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
1         Sedan  27150   2  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [80]:
df[df['Make'] == 'Nissan']

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
4        Pickup  32340   5

In [81]:
# Combining filtering conditions
df[(df['Make'] == 'Nissan') & (df['Year'] >= 2015)]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
4        Pickup  32340   5

### String Operations

In [82]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [83]:
# Replacing spaces with underscores
df['Vehicle_Style'].str.replace(" ", "_")

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

### Summarizing Operations

In [84]:
df.MSRP.mean()

30186.0

In [85]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [87]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP    id
count     5.00       4.00              5.00      5.00  5.00
mean   2010.40     202.75              4.40  30186.00  3.00
std      11.26      51.30              0.89  18985.04  1.58
min    1991.00     138.00              4.00   2000.00  1.00
25%    2010.00     180.00              4.00  27150.00  2.00
50%    2017.00     206.00              4.00  32340.00  3.00
75%    2017.00     228.75              4.00  34450.00  4.00
max    2017.00     261.00              6.00  54990.00  5.00

In [88]:
df.Make.nunique()

4

In [90]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
id                   5
dtype: int64

### Missing Values

In [91]:
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP     id  
0          False  False  False  
1          False  False  False  
2          False  False  False  
3          False  False  False  
4          False  False  False

In [92]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

### Grouping

In [93]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

### Getting the NumPy Arrays

In [95]:
# Getting the underlying NumPy array for the 'MSRP' column 
df.MSRP.values 

array([ 2000, 27150, 54990, 34450, 32340], dtype=int64)

In [96]:
df.to_dict(orient="records")

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000,
  'id': 1},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150,
  'id': 2},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990,
  'id': 3},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450,
  'id': 4},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340,
  'id': 5}]

### Homework

In [110]:
# Question 1
print(pd.__version__)

2.1.0


In [111]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

In [112]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [113]:
# Question 2
print(len(df.columns))

10


In [114]:
# Question 3
print(df.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


In [115]:
# Question 4
print(df.ocean_proximity.nunique())

5


In [116]:
# Question 5
print(df[df["ocean_proximity"]=="NEAR BAY"].median_house_value.mean())

259212.31179039303


In [117]:
# Question 6
total_bedrooms_avg = df.total_bedrooms.mean()
print(f"Average value before filling missing values: {round(total_bedrooms_avg, 3)}")
df.total_bedrooms.fillna(total_bedrooms_avg, inplace=True)
print(df.total_bedrooms.isna().sum())
print(f"Average value after filling missing values: {round(df.total_bedrooms.mean(), 3)}")

Average value before filling missing values: 537.871
0
Average value after filling missing values: 537.871


In [119]:
df.ocean_proximity.value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [129]:
# Question 7
X = df[df.ocean_proximity == "ISLAND"][["housing_median_age", "total_rooms", "total_bedrooms"]].values
print(X.shape)
XTX = np.matmul(X.T, X)
XTX_inverse = np.linalg.inv(XTX)
y = np.array([950, 1300, 800, 1000, 1300])
w = np.matmul(np.matmul(XTX_inverse, X.T), y)
print(w[-1])

(5, 3)
5.699229455065586
